
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:study
    username: sa
    password:

cloud:
  aws:
    credentials:
      accessKey: AKIAT4CI35TJC5FP2T4S
      secretKey: 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
    s3:
      bucket: arn:aws:s3:::study-img
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error